DROP TABLE IF EXISTS AVIONES;
CREATE TABLE AVIONES(
ID INT AUTO_INCREMENT PRIMARY KEY,
MARCA VARCHAR(50) NOT NULL,
MODELO VARCHAR(50) NOT NULL,
MATRICULA VARCHAR(50) NOT NULL,
FECHAENTRADASERVICIO DATE NOT NULL);

INSERT INTO AVIONES VALUES (DEFAULT, 'AIRBUS', 'A220', 'ABC123', '2023-11-02'), (DEFAULT, 'AIRBUS', 'A340', 'ABC456', '2021-08-02');